### ISSUE TITLE
How to use YOLO_full.ckpt for detection?

### ISSUE THREAD

**Issue by joei1981** [gliese581gg/YOLO_tensorflow#12]
I tried to use YOLO_weight_extractor by "yolo.weights" and have made a "YOLO_full.ckpt" successfully. After then, I refered "YOLO_small_tf.py" to make a new "YOLO_full_tf.py" by myself for detection based on "YOLO_full.ckpt", but the parameters (x, y, w, h) of detected bounding boxes were very strange (some very big integers). I think there should be some problems in "YOLO_full_tf.py". If possible, could you please tell me about difference between "YOLO_small_tf.py" and "YOLO_full_tf.py" ?

I will appreciate your guidance.

**Comment by msegala** [comment]
any luck with this? I am starting to do the same thing and thought we could help each other. Would you mind posting your weight file along with the code? I will take a look and see if I can get it working on my images.

**Comment by joei1981** [comment]
Thank you so much for your interesting.

I have shared weights file with your gmail, please make a try.
If you find any problems, please feel free to tell me.

**Comment by haoran1062** [comment]
hi,I try to convert the yolo-tiny.weights(download form YOLO),and it success to create the yolo-tiny.ckpt,but when I test that yolo-tiny.ckpt(python YOLO_tiny_tf.py):
'Detect from person.jpg class : aeroplane , [x,y,w,h]=[168759,167882,13921232896,8060527616], Confidence = 92084104.0 Traceback (most recent call last): File "YOLO_tiny_tf.py", line 237, in <module> main(sys.argv) File "YOLO_tiny_tf.py", line 232, in main yolo = YOLO_TF(argvs) File "YOLO_tiny_tf.py", line 30, in **init** if self.fromfile is not None: self.detect_from_file(self.fromfile) File "YOLO_tiny_tf.py", line 124, in detect_from_file self.detect_from_cvmat(img) File "YOLO_tiny_tf.py", line 116, in detect_from_cvmat self.show_results(img,self.result) File "YOLO_tiny_tf.py", line 203, in show_results cv2.rectangle(img_cp,(x-w,y-h),(x+w,y+h),(0,255,0),2) OverflowError: signed integer is less than minimum'
I think we have the same question?

**Comment by joei1981** [comment]
To haoran1062:

Yes, I think so. We encountered the similar problem, but actually I have not resolved it.

**Comment by haoran1062** [comment]
Just 1 min ago,I try the yolo-small.weights -> yolo-small.ckpt,and to test it, and it success to load and to label form my camera! I think maybe my download(yolo-tiny.weights) maybe have some error or the `YOLO_tiny_builder.py` have some bug... I don't sure,my guess... And I'm trying to convert my weights(although my weights are trainnig by tiny),I try to run my training with small and run conv again,BTW,which country you are?my English is not good T^T

**Comment by joei1981** [comment]
In my understanding, except yolo-small.ckpt, the source for detection should be revised somehow for promising a successful execution, but I do not how to revise.
I am from China.

**Comment by haoran1062** [comment]
> joei1981
> 我靠 俩国人在github用英语讨论半天问题 233...

**Comment by joei1981** [comment]
You can contact me by xurong1981@gmail.com

**Comment by xieyulai** [comment]
@joei1981 @haoran1062 @msegala do you resovle this issue?

**Comment by strickon** [comment]
Yolo uses the coco dataset which has 80 classes.  It just can't be swapped in with small or tiny.  You have to make the new network.  I am trying to generate the ckpt file but I am not on linux so I need the source to the modified darknet.  If you have the yolo.ckpt file, can you share with me.

I was looking at yolo v2 which I realize this system doesn't support.

**Comment by hust-kevin** [comment]
@joei1981  我访问不了谷歌云盘，可以将三个网络的权重文件以百度云盘的形式分享给我吗，我的邮箱为   
zhongbing_hu@hust.edu.cn

**Comment by cococyx** [comment]
@joei1981 Could you please share the yolo.ckpt file(YOLO_small.ckpt / YOLO_tiny.ckpt / YOLO_face.ckpt). Thanks a lot. My email is sisiwuxi@hotmail.com

**Comment by YunYang1994** [comment]
hope this helps you ! https://github.com/YunYang1994/tensorflow-yolov3

**Comment by cococyx** [comment]
Thanks so much for your reply.

________________________________
发件人: YangYun <notifications@github.com>
发送时间: 2018年12月13日 10:46
收件人: gliese581gg/YOLO_tensorflow
抄送: cococyx; Comment
主题: Re: [gliese581gg/YOLO_tensorflow] How to use YOLO_full.ckpt for detection? (#12)


hope this helps you ! https://github.com/YunYang1994/tensorflow-yolov3

―
