### ISSUE TITLE
OverflowError: signed integer is less than minimum

### ISSUE THREAD

**Issue by gambitvk** [gliese581gg/YOLO_tensorflow#20]
HI ,

I have extracted the weights for YOLO tiny and try to use your code to predicted the person.jpg... adn the follow error came up.

Loading complete!

Detect from test/person.jpg
    class : bird , [x,y,w,h]=[4764318,-2995212,997766463488,135557791744], Confidence = 17189599232.0
Traceback (most recent call last):
  File "YOLO_tiny_tf.py", line 237, in <module>
    main(sys.argv)
  File "YOLO_tiny_tf.py", line 232, in main
    yolo = YOLO_TF(argvs)
  File "YOLO_tiny_tf.py", line 30, in __init__
    if self.fromfile is not None: self.detect_from_file(self.fromfile)
  File "YOLO_tiny_tf.py", line 124, in detect_from_file
    self.detect_from_cvmat(img)
  File "YOLO_tiny_tf.py", line 116, in detect_from_cvmat
    self.show_results(img,self.result)
  File "YOLO_tiny_tf.py", line 203, in show_results
    cv2.rectangle(img_cp,(x-w,y-h),(x+w,y+h),(0,255,0),2)
OverflowError: signed integer is less than minimum

Any ideas ? ... the confident level looks way too big .

I have also tried to use the yolo_small weights .. and basically I got NANs in everything.

**Comment by gambitvk** [comment]
I saw a similar issue being raised ... and he used the wrong config file ... here is How i prodcued the weights text files ...
./darknet yolo test cfg/yolo-tiny.cfg tiny-yolo-voc.weights

so I assume I used the correct config ...
